# name, on, jobs의 세가지 구성(필수)

name: 'My first github action'
# workflow의 고유 이름

on: [ 'push', 'pull-request' ]
# 어느 시점에서 실행 (push, comment, commit 등 어느 시점에)
# 중복되는 시점이 여러개면 모든 yaml이 동시에 실행됨.

jobs:
  first-job:
    name: 'first job'
    
    runs-on: ubuntu-latest
    #os windows-latest macos-latest ubuntu-latest

    - name: output value 1
      shell: bash
      run: |
        echo "Hello World"

    - name: output value 2
      if: github.event_name == 'pull request'
      shell: bash
      run: |
        echo "Hello World"

  second-job:
  # build server
    name: 'second job'
    if: github.event_name == 'pull_request'
    
    runs-on: ubuntu-latest
    #os windows-latest macos-latest ubuntu-latest

    - name: output value 2
      shell: bash
      run: |
        echo "Hello World"
