# name, on, jobs의 세가지 구성(필수)

name: 'My first github action'
# workflow의 고유 이름

on: push
# 어느 시점에서 실행 (push, comment, commit 등 어느 시점에)
# 중복되는 시점이 여러개면 모든 yaml이 동시에 실행됨.

jobs:
  first-job:
  # build server
    name: 'first job'

    strategy:
      matrix:
        os: [ 'os windows-latest', 'macos-latest', 'ubuntu-latest' ]
    
    runs-on: ${{ matrix.os }}
    #os windows-latest macos-latest ubuntu-latest
    steps: 
    - name: output value from ${{ matrix.os }}
      id: first
      shell: bash
      run: |
       echo "OS: ${{ matrix.os }}"